const router=require('express').Router();
const {requireAuth}=require('../../../common/middleware/authorize');
const rateLimit=require('../../../common/middleware/rateLimit');
const v=require('../validations/policy.validation');
const profile=require('../controllers/profile.controller');
const policy=require('../controllers/policy.controller');
const match=require('../controllers/matching.controller');
const application=require('../controllers/application.controller');
const validate=(parse)=>(req,res,next)=>{try{req.validated=parse(req);next();}catch(error){next(error);}};
const subjectQuery=req=>({subjectType:v.subject(req.query.subjectType||'personal')});
const idParam=req=>({id:v.id(req.params.id)});
const recordParam=req=>({id:v.uuid(req.params.id)});
router.get('/policies',validate(subjectQuery),policy.list);
router.get('/policies/:id',validate(idParam),policy.detail);
router.use(requireAuth);
router.get('/policies/:id/benefit-check',validate(idParam),policy.benefits);
router.get('/profiles/:subjectType',validate(req=>({subjectType:v.subject(req.params.subjectType)})),profile.get);
router.put('/profiles/:subjectType',validate(req=>{const subjectType=v.subject(req.params.subjectType);return {subjectType,input:v.profile(req.body,subjectType)};}),profile.save);
router.get('/favorites',policy.favorites);
router.put('/policies/:id/favorite',validate(idParam),policy.favorite);
router.delete('/policies/:id/favorite',validate(idParam),policy.favorite);
router.get('/matches',validate(subjectQuery),match.list);
router.post('/matches',rateLimit(20,60000),validate(req=>({subjectType:v.subject(req.body.subjectType)})),match.create);
router.get('/matches/:id',validate(recordParam),match.detail);
router.get('/applications',validate(subjectQuery),application.list);
router.post('/applications',validate(req=>({id:v.id(req.body.policyId),declaration:v.benefitDeclaration(req.body.benefitDeclaration)})),application.create);
router.get('/applications/:id',validate(recordParam),application.detail);
router.patch('/applications/:id',validate(req=>({...recordParam(req),input:v.application(req.body)})),application.save);
router.post('/applications/:id/withdraw',validate(req=>({...recordParam(req),input:{version:v.version(req.body.version)}})),application.withdraw);
router.post('/applications/:id/materials',validate(req=>({...recordParam(req),input:{code:v.id(req.body.code),fileId:v.uuid(req.body.fileId),version:v.version(req.body.version)}})),application.material);
router.post('/applications/:id/submit',validate(req=>({...recordParam(req),input:{key:v.id(req.body.key),version:v.version(req.body.version)}})),application.submit);
router.patch('/applications/:id/external-progress',validate(req=>({...recordParam(req),input:v.progress(req.body)})),application.progress);
module.exports=router;
