import PropTypes from 'prop-types';
import {Link} from 'react-router-dom';
import {RightOutline,FileOutline,TeamFill} from 'antd-mobile-icons';
import hero from '../assets/policy-hero.png';
import {date,eligibility,statuses} from '../utils/format';

export function Icon({name='document',size=22}) {
  const paths={arrow:'M5 12h14m-5-5 5 5-5 5',back:'m14 5-7 7 7 7',search:'M21 21l-5-5M18 10a8 8 0 1 1-16 0 8 8 0 0 1 16 0',document:'M6 3h9l4 4v14H6zM14 3v5h5M9 12h7M9 16h7',user:'M16 7a4 4 0 1 1-8 0 4 4 0 0 1 8 0M4 21v-2a8 8 0 0 1 16 0v2z',company:'M4 21V5l11-3v19M15 10h5v11M7 8h4M7 12h4M7 16h4',check:'m5 12 4 4L19 6',clock:'M12 8v5l3 2M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0',star:'m12 2 3 6 7 1-5 5 1 7-6-3-6 3 1-7-5-5 7-1z',book:'M12 5C8 2 4 2 2 3v17c4-1 7-1 10 1 3-2 6-2 10-1V3c-3-1-6-1-10 2v16',cap:'m2 9 10-5 10 5-10 5zM6 11v6q6 5 12 0v-6M22 9v8',upload:'M12 16V3m-5 5 5-5 5 5M4 15v6h16v-6',info:'M12 11v6M12 7h.01M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0'};
  return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={paths[name]||paths.document}/></svg>;
}
Icon.propTypes={name:PropTypes.string,size:PropTypes.number};
export function Header({title,back='/policy-match',backLabel,action}){return <header className={'pm-header'+(backLabel?' pm-header--labelled':'')}><Link to={back} aria-label={backLabel||'返回'}><Icon name="back"/>{backLabel&&<span>{backLabel}</span>}</Link><strong>{title}</strong>{action||<Link to="/policy-match/records" aria-label="申报记录"><Icon name="clock"/></Link>}</header>;}
Header.propTypes={title:PropTypes.string,back:PropTypes.string,backLabel:PropTypes.string,action:PropTypes.node};
export function Hero({title,subtitle='人才 · 就业 · 创业 · 惠企',compact=false}){return <section className={'pm-hero '+(compact?'pm-hero--compact':'')} style={{backgroundImage:'url('+hero+')'}}><div><small>POLICY SERVICE</small><h1>{title}</h1><p>{subtitle}</p><span className="pm-demo">通用演示政策 <Icon name="arrow" size={13}/></span></div></section>;}
Hero.propTypes={title:PropTypes.node,subtitle:PropTypes.string,compact:PropTypes.bool};
export function Section({title,link,to,children}){return <section className="pm-section"><div className="pm-section-title"><h2>{title}</h2>{to&&<Link to={to}>{link||'查看全部'} <Icon name="arrow" size={16}/></Link>}</div>{children}</section>;}
Section.propTypes={title:PropTypes.node,link:PropTypes.string,to:PropTypes.string,children:PropTypes.node};
export function Notice({children,error=false}){return children?<div role={error?'alert':'note'} className={'pm-notice '+(error?'pm-notice--error':'')}><Icon name="info" size={18}/><div>{children}</div></div>:null;}
Notice.propTypes={children:PropTypes.node,error:PropTypes.bool};
export function State({loading,error,retry,children}){if(loading)return <div className="pm-skeleton" role="status" aria-label="正在加载"><i/><i/><i/></div>;if(error)return <div className="pm-card"><Notice error>{error}</Notice><button onClick={retry} className="pm-secondary">重新加载</button></div>;return children;}
State.propTypes={loading:PropTypes.bool,error:PropTypes.string,retry:PropTypes.func,children:PropTypes.node};
export function Empty({title='暂时没有记录',text='完成一次匹配，发现属于你的政策机会',to='/policy-match/profile',label='开始完善画像'}){return <div className="pm-empty"><span className="pm-iconbox"><Icon name="document" size={30}/></span><h3>{title}</h3><p>{text}</p>{to&&<Link className="pm-secondary" to={to}>{label} <Icon name="arrow" size={16}/></Link>}</div>;}
Empty.propTypes={title:PropTypes.string,text:PropTypes.string,to:PropTypes.string,label:PropTypes.string};
export function Footer(){return <footer className="pm-footer">演示政策数据，仅供体验<br/>最终资格以主管部门认定为准。</footer>;}
export function PolicyCard({policy,snapshot,compact=false,home=false,selected,onSelect}){const to='/policy-match/policies/'+policy.id+(snapshot?'?match='+snapshot:'');if(home) return <Link to={to} className="pm-home-policy"><span className="pm-iconbox">{policy.category==='人才'?<TeamFill/>:<FileOutline/>}</span><div className="pm-home-policy-copy"><h3>{policy.title}</h3><small>{policy.category} · {policy.subjectType==='company'?'企业发展':'个人支持'}</small><p>{policy.description}</p></div><div className="pm-home-policy-benefit"><strong>{policy.benefit}</strong>{policy.eligibility&&<span className={'pm-badge '+policy.eligibility}>{eligibility[policy.eligibility]}</span>}</div></Link>;return <article className={'pm-policy-card '+(compact?'is-compact':'')}><Link to={to} className="pm-policy-main"><span className="pm-iconbox"><Icon name={policy.category==='人才'?'cap':policy.subjectType==='company'?'company':'document'} size={26}/></span><div className="pm-policy-copy"><h3>{policy.title}</h3><small>{policy.category} · {policy.channel==='internal'?'站内申报':'外部办理'}</small>{!compact&&<p>{policy.description.slice(0,50)}…</p>}</div>{policy.score!==undefined&&<div className="pm-score"><strong>{policy.score}<small>%</small></strong><span className={'pm-badge '+policy.eligibility}>{eligibility[policy.eligibility]}</span></div>}</Link><div className="pm-policy-meta"><strong>{policy.benefit}</strong><span>{date(policy.endsAt)}截止</span>{compact&&<Icon name="arrow" size={15}/>}</div>{!compact&&<div className="pm-policy-bottom">{onSelect&&<label><input type="checkbox" checked={selected} onChange={onSelect}/>加入对比</label>}<Link to={to}>查看判断依据 <Icon name="arrow" size={15}/></Link></div>}</article>;}
PolicyCard.propTypes={policy:PropTypes.object.isRequired,snapshot:PropTypes.string,compact:PropTypes.bool,home:PropTypes.bool,selected:PropTypes.bool,onSelect:PropTypes.func};
export function ApplicationCard({application,compact=false}){if(compact) return <Link to={'/policy-match/records/'+application.id} className="pm-home-application pm-card"><span className="pm-iconbox"><FileOutline/></span><div><h3>{application.policy.title}</h3><small>{application.policy.category} · {application.policy.channel==='internal'?'站内申报':'外部办理'}</small></div><strong>{statuses[application.status]}</strong><RightOutline/></Link>;return <Link to={'/policy-match/records/'+application.id} className={'pm-application pm-card '+(application.status==='supplement_required'?'needs-action':'')}><span className="pm-iconbox"><Icon name="document"/></span><div><h3>{application.policy.title}</h3><p>{application.policy.channel==='internal'?'站内模拟申报':'外部办理'} · {statuses[application.status]}</p><small>{date(application.updatedAt)}更新</small></div><Icon name="arrow" size={17}/></Link>;}
ApplicationCard.propTypes={application:PropTypes.object.isRequired,compact:PropTypes.bool};
