const test=require('node:test');
const assert=require('node:assert/strict');
const {randomUUID}=require('node:crypto');
const sharp=require('sharp');
const app=require('../src/app');
const db=require('../src/config/database');
const {issueAccessToken}=require('../src/system/auth').service;
test('政策真实接口：画像隔离、快照、材料权限、并发提交和外部进度',async()=>{
  const userId='policy-test-'+randomUUID(),other='policy-test-'+randomUUID();
  const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));
  const base='http://127.0.0.1:'+server.address().port+'/api/policy-match';
  const token=issueAccessToken({userId,roles:['citizen']});
  const otherToken=issueAccessToken({userId:other,roles:['citizen']});
  const request=async(path,method='GET',body,auth=token)=>{const res=await fetch(base+path,{method,headers:{Authorization:auth?'Bearer '+auth:'','Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});return {status:res.status,...await res.json()};};
  const files=[];
  try{
    assert.equal((await request('/policies?subjectType=personal','GET',null,'')).status,200);
    assert.equal((await request('/profiles/personal','GET',null,'')).status,401);
    assert.equal((await request('/applications/bad-id')).status,400);
    assert.equal((await request('/profiles/personal','PUT',{version:0,payload:{age:-1}})).status,400);
    const payload={age:28,education:'本科',employment:'已就业',socialMonths:12,graduationYear:2024};
    const profile=await request('/profiles/personal','PUT',{version:0,payload});
    assert.equal(profile.status,200);
    assert.deepEqual((await request('/profiles/company')).data.payload,{});
    assert.deepEqual((await request('/profiles/personal','GET',null,otherToken)).data.payload,{});
    assert.equal((await request('/profiles/personal','PUT',{version:0,payload})).status,409);
    const matched=await request('/matches','POST',{subjectType:'personal'});
    assert.equal(matched.status,200);assert.equal(matched.data.results.find(p=>p.id==='youth').eligibility,'eligible');
    assert.equal((await request('/matches/'+matched.data.id,'GET',null,otherToken)).status,404);
    await request('/profiles/personal','PUT',{version:1,payload:{...payload,age:40}});
    assert.equal((await request('/matches/'+matched.data.id)).data.profile.age,28);
    await request('/profiles/personal','PUT',{version:2,payload});
    assert.equal((await request('/applications','POST',{policyId:'youth'})).status,400);
    assert.equal((await request('/applications','POST',{policyId:'youth',benefitDeclaration:'received'})).status,400);
    const drafts=await Promise.all([request('/applications','POST',{policyId:'youth',benefitDeclaration:'none'}),request('/applications','POST',{policyId:'youth',benefitDeclaration:'none'})]);
    assert.equal(drafts[0].data.id,drafts[1].data.id);
    let row=drafts[0].data;
    assert.equal((await request('/policies/housing/benefit-check')).data.blocked,true);
    assert.equal((await request('/applications','POST',{policyId:'housing',benefitDeclaration:'none'})).status,409);
    await request('/profiles/personal','PUT',{version:0,payload},otherToken);
    const competing=await Promise.all(['youth','housing'].map(policyId=>request('/applications','POST',{policyId,benefitDeclaration:'none'},otherToken)));
    assert.deepEqual(competing.map(r=>r.status).sort(),[200,409]);
    assert.equal((await request('/applications/'+row.id,'GET',null,otherToken)).status,404);
    row=(await request('/applications/'+row.id,'PATCH',{version:row.version,payload:{applicant:'测试申请人',phone:'13800005678',purpose:'接口测试'}})).data;
    assert.equal((await request('/applications/'+row.id,'PATCH',{version:0,payload:{applicant:'冲突'}})).status,409);
    assert.equal((await request('/applications/'+row.id+'/submit','POST',{version:row.version,key:'empty-materials'})).status,400);
    const pdfForm=new FormData();
    pdfForm.append('file',new Blob(['%PDF-1.4\n%%EOF'],{type:'application/pdf'}),'not-an-image.pdf');
    const pdfUpload=await fetch(base.replace('/policy-match','/files'),{method:'POST',headers:{Authorization:'Bearer '+token},body:pdfForm});
    assert.equal(pdfUpload.status,201);
    const pdf=(await pdfUpload.json()).data;files.push(pdf.id);
    assert.equal((await request('/applications/'+row.id+'/materials','POST',{version:row.version,code:row.policy.materials[0].code,fileId:pdf.id})).status,400);
    for(const material of row.policy.materials){
      const form=new FormData();
      const fixture=await sharp({create:{width:32,height:32,channels:3,background:'#64746c'}}).png().toBuffer();
      form.append('file',new Blob([fixture],{type:'image/png'}),'test-material.png');
      const uploaded=await fetch(base.replace('/policy-match','/files'),{method:'POST',headers:{Authorization:'Bearer '+token},body:form});
      assert.equal(uploaded.status,201);
      const file=(await uploaded.json()).data;files.push(file.id);
      const stream=await fetch(base.replace('/policy-match','/files/')+file.id,{headers:{Authorization:'Bearer '+token}});
      assert.equal(stream.status,200);
      const downloaded=await sharp(Buffer.from(await stream.arrayBuffer())).metadata();
      assert.equal(downloaded.width,32);assert.equal(downloaded.height,32);
      assert.ok(['jpeg','png'].includes(downloaded.format));
      assert.equal((await fetch(base.replace('/policy-match','/files/')+file.id,{headers:{Authorization:'Bearer '+otherToken}})).status,403);
      const foreign=await request('/applications/'+row.id+'/materials','POST',{version:row.version,code:material.code,fileId:file.id},otherToken);
      assert.equal(foreign.status,404);
      const attached=await request('/applications/'+row.id+'/materials','POST',{version:row.version,code:material.code,fileId:file.id});
      assert.equal(attached.status,200);row=attached.data;
    }
    const firstMaterial=row.materials[0];
    await db.policyApplicationMaterial.update({where:{applicationId_code:{applicationId:row.id,code:firstMaterial.code}},data:{fileId:pdf.id}});
    assert.equal((await request('/applications/'+row.id+'/submit','POST',{version:row.version,key:'legacy-pdf'})).status,400);
    row=(await request('/applications/'+row.id+'/materials','POST',{version:row.version,code:firstMaterial.code,fileId:firstMaterial.fileId})).data;
    row=(await request('/applications/'+row.id,'PATCH',{version:row.version,payload:{benefitDeclaration:'received'}})).data;
    assert.equal((await request('/applications/'+row.id+'/submit','POST',{version:row.version,key:'blocked-benefits'})).status,400);
    row=(await request('/applications/'+row.id,'PATCH',{version:row.version,payload:{benefitDeclaration:'none'}})).data;
    const submitted=await Promise.all([request('/applications/'+row.id+'/submit','POST',{version:row.version,key:'same-key'}),request('/applications/'+row.id+'/submit','POST',{version:row.version,key:'same-key'})]);
    assert.equal(submitted[0].status,200);assert.equal(submitted[1].status,200);assert.equal(submitted[0].data.receipt,submitted[1].data.receipt);
    assert.equal(submitted[0].data.status,'submitted');
    assert.equal((await request('/applications/'+row.id,'PATCH',{version:submitted[0].data.version,payload:{applicant:'篡改'}})).status,409);
    let external=(await request('/applications','POST',{policyId:'graduate',benefitDeclaration:'none'})).data;
    assert.equal(external.status,'preparing');
    external=(await request('/applications/'+external.id,'PATCH',{version:external.version,payload:{benefitDeclaration:'unknown'}})).data;
    assert.equal((await request('/applications/'+external.id+'/external-progress','PATCH',{version:external.version,status:'visited_external',prepared:[]})).status,400);
    external=(await request('/applications/'+external.id,'PATCH',{version:external.version,payload:{benefitDeclaration:'none'}})).data;
    assert.equal((await request('/applications/'+external.id+'/external-progress','PATCH',{version:external.version,status:'approved',prepared:[]})).status,400);
    external=(await request('/applications/'+external.id+'/external-progress','PATCH',{version:external.version,status:'visited_external',prepared:['identity']})).data;
    assert.equal(external.status,'visited_external');
    await request('/policies/youth/favorite','PUT');
    assert.equal((await request('/favorites')).data.length,1);
    await request('/policies/youth/favorite','DELETE');
    assert.equal((await request('/favorites')).data.length,0);
    const draft=(await request('/applications','POST',{policyId:'skills',benefitDeclaration:'none'})).data;
    assert.equal((await request('/applications/'+draft.id+'/withdraw','POST',{version:draft.version},otherToken)).status,404);
    assert.equal((await request('/applications/'+draft.id+'/withdraw','POST',{version:draft.version+1})).status,409);
    const withdrawn=await request('/applications/'+draft.id+'/withdraw','POST',{version:draft.version});
    assert.equal(withdrawn.status,200);
    assert.equal(withdrawn.data.status,'withdrawn');
    assert.equal(withdrawn.data.events.at(-1).status,'withdrawn');
    assert.notEqual((await request('/applications','POST',{policyId:'skills',benefitDeclaration:'none'})).data.id,draft.id);
    await db.policyApplication.update({where:{id:row.id},data:{status:'approved'}});
    assert.equal((await request('/applications','POST',{policyId:'youth'})).data.id,row.id);
    assert.equal((await request('/applications/'+row.id+'/withdraw','POST',{version:submitted[0].data.version})).status,409);
  }finally{
    await db.policyApplication.deleteMany({where:{userId}});
    await db.policyApplication.deleteMany({where:{userId:other}});
    await db.policyMatchProfile.deleteMany({where:{userId:other}});
    for(const fileId of files)await fetch(base.replace('/policy-match','/files/')+fileId,{method:'DELETE',headers:{Authorization:'Bearer '+token}});
    await db.policyFavorite.deleteMany({where:{userId}});
    await db.policyMatchSnapshot.deleteMany({where:{userId}});
    await db.policyMatchProfile.deleteMany({where:{userId}});
    server.closeAllConnections();await new Promise(r=>server.close(r));
  }
});
