const router = require('express').Router();
const { requireAuth, requireRole } = require('../../../common/middleware/authorize');
const activity = require('../controllers/activity.controller');
const wallet = require('../controllers/wallet.controller');
const merchant = require('../controllers/merchant.controller');
const verification = require('../controllers/verification.controller');
router.get('/activities', activity.list);
router.get('/activities/:id', activity.get);
router.get('/merchants', merchant.list);
router.use(requireAuth);
router.get('/wallet', wallet.list);
router.post('/wallet', wallet.claim);
router.get('/wallet/:id', wallet.get);
router.post('/wallet/:id/credential', verification.credential);
router.use('/verifications', requireRole('merchant'));
router.get('/verifications', verification.list);
router.post('/verifications/preview', verification.preview);
router.post('/verifications', verification.confirm);
module.exports = router;
